/*


const { getAllTickets } = require("./conn/tickets");
getAllTickets()
.then(tickets=>{
    console.log(tickets)
})
.catch(err=>{
    console.log(err)
})
///////////////////////////////////////////////////////////////////
const{getTicketsByID}=require("./conn/tickets")
getTicketsByID()
.then(tickets=>{
    console.log(tickets)
})
.catch(err=>{
    console.log(err)
})
////////////////////////////////////////////////////////////////////////
const{addTickets}=require("./conn/tickets")
addTickets()
.then(tickets=>{
    console.log(tickets)
})
.catch(err=>{
    console.log(err)
})
//////////////////////////////////////////////////////////////////////////
const{UpdateTickets}=require("./conn/tickets")
UpdateTickets()
.then(tickets=>{
    console.log(tickets)
})
.catch(err=>{
    console.log(err)
})
///////////////////////////////////////////////////////////////////////////////
const{removeTickets}=require("./conn/tickets")
removeTickets()
.then(tickets=>{
    console.log(tickets)
})
.catch(err=>{
    console.log(err)
})
////////////////////////////////////////////////////////////////////////////////
const{getTicketsByUserID}=require("./conn/tickets")
getTicketsByUserID()
.then(tickets=>{
    console.log(tickets)
})
.catch(err=>{
    console.log(err)
})
///////////////////////////////////////////////////////////////////////////////////////////
const{getTicketsByUserName}=require("./conn/tickets")
getTicketsByUserName()
.then(tickets=>{
    console.log(tickets)
})
.catch(err=>{
    console.log(err)
})

*/
